# Site settings
title:          Adam Lombard
description:    "Homepage of Adam Lombard -- novelist, developer, co-author of Manly Hero"
url:            "http://www.adamlombard.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Adam
  url:          http://www.adamlombard.com
  email:        siradamlombard@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
